Feat/adding timeout action
qredo/fusionchain pull request #93
Opened 2023-10-09 08:33 UTC by khalifaT

In this PR, we are adding TTL (Time To Live) for a specific action.

A user will be able to specify a TTL for his request. Before the expiration of this TTL, the approver may accept or not this action.
Otherwise, it will be automatically rejected.

Next Improvement:
Upgrade of the frontEnd  to take into consideration this new field

2023-10-09 08:50 UTC, Lazar955 requested changes

2023-10-09 08:50 UTC, Lazar955 commented on blockchain/proto/fusionchain/policy/action.proto
> +  uint64 creation_time = 7;
not to nitpick naming conventions or anything, but "_time" doesn't really portray that this is actually a timestamp, and I also don't like having "type" in the name of the property. A much cleaner (IMO) name would be `created_at`, quite universal naming-wise.

2023-10-09 08:50 UTC, Lazar955 commented on blockchain/proto/fusionchain/policy/action.proto
> +  ACTION_STATUS_REJECTED = 4;
Also, as this isn't a rejection, can we call it `_EXPIRED`

2023-10-09 08:50 UTC, Lazar955 commented on blockchain/x/policy/keeper/msg_server_approve_action.go
> +	if act.Ttl+act.CreationTime < uint64(ctx.BlockHeight()) {
is `TTL` in seconds?

2023-10-09 08:50 UTC, Lazar955 commented on blockchain/x/policy/keeper/msg_server_approve_action.go
> +	if act.Ttl+act.CreationTime < uint64(ctx.BlockHeight()) {
Shouldn't `ctx.BlockHeight()` actually be `ctx.BlockTime()` or otherwise `TTL` is the number of blocks, and `CreationTime` is actually the block height at that time

2023-10-09 08:55 UTC, Pitasi requested changes
I think that it's more useful if TTL is the block height when the action expires.

For example I should be able to say "this action is valid until block 131", and not "this action is valid for 30 blocks. I don't know exactly what block my action is going to be included, let's say it stays in mempool for 15 minutes and then it's valid for 30 more blocks, it might not be what I intended.

Does it make sense?

2023-10-09 08:58 UTC, Pitasi commented on blockchain/proto/fusionchain/policy/action.proto
> +  uint64 creation_time = 7;
> not to nitpick naming conventions

I would consider it nitpicking if it was a variable inside a method but it's okay be more strict about protobuf fields naming because these are going to end up in public facing APIs that should be as clear as possible 😁

2023-10-09 08:59 UTC, Pitasi commented on blockchain/x/policy/keeper/msg_server_approve_action.go
> +	if act.Ttl+act.CreationTime < uint64(ctx.BlockHeight()) {
it's more easy to talk about block heights than timestamps

timestamps lead to non-determinism and chain halts 😨

2023-10-09 08:59 UTC, khalifaT commented on blockchain/x/policy/keeper/msg_server_approve_action.go
> +	if act.Ttl+act.CreationTime < uint64(ctx.BlockHeight()) {
Both of them are in Blocks.
TTL is the  number of blocks to wait.

2023-10-09 11:35 UTC, Pitasi requested changes

2023-10-09 11:35 UTC, Pitasi commented on blockchain/proto/fusionchain/policy/action.proto
> +  //  action can be approved or rejected.
```suggestion
  // TTL (time to live) is the block height up until this action can be
  // approved or rejected.
  uint64 ttl = 7;
```

comment should go above definition, I also reworded it a bit

2023-10-09 11:35 UTC, Pitasi commented on blockchain/x/policy/keeper/actions.go
> +	// may be we have to check the value of TTL here, if it is not defined we have to use the default value
```suggestion
```

I don't think it's needed, the default value (`0`) means there is no timeout

2023-10-09 11:35 UTC, Pitasi commented on blockchain/x/policy/keeper/msg_server_approve_action.go
> +	if act.Ttl < uint64(ctx.BlockHeight()) {
```suggestion
	if act.Ttl > 0 && act.Ttl < uint64(ctx.BlockHeight()) {
```

2023-10-09 11:45 UTC, Lazar955 commented on blockchain/proto/fusionchain/policy/action.proto
> +  //  action can be approved or rejected.
I think TTL should be renamed to something more intuitive. Because when I see TTL without reading the protobuf def in code, I would automatically assume it is a number of seconds (as it usually is). So we should rename it to something more (or less obvious so people don't just assume things) like `BTL` (blocks to live) or `BlocksValid` or whatever to indicate a number of blocks valid. I know this might be considered "trivial" but as you say this is our public "interface" and it should really be intuitive.

2023-10-09 15:46 UTC, Pitasi approved these changes

2023-10-10 08:41 UTC, Lazar955 approved these changes

2023-10-10 08:42 UTC, merged